name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - feature/guide-automator-integration

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
# TODO: Change variable to your image's name.
  IMAGE_NAME: guide-automator-puppeteer-image

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: run guide automator
        run: |
          docker build -t micro-livraria .
          docker run -d --rm -p 5000:5000 -p 3000:3000 micro-livraria
          docker run --rm -v $(pwd)/output:/usr/src/output -v $(pwd)/.guide-automator:/usr/src/guide-automator icaroerasmo/guide-automator-puppeteer -d -i /usr/src/guide-automator/livraria.md -cv /usr/src/guide-automator/cover.html -o /usr/src/output

