name: Docker

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - feature/guide-automator-integration

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
# TODO: Change variable to your image's name.
  IMAGE_NAME: guide-automator-puppeteer-image

jobs:
  push:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: run guide automator
        run: |
          # Captures host ip
          hostip=$(ip a s eth0 | egrep -o 'inet [0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' | cut -d' ' -f2)
          
          # Replaces host ip into guide automator script
          sed -i 's/http:\/\/localhost'/"http:\/\/$hostip"/g .guide-automator/livraria.md
          
          # Builds micro livraria image
          docker build -t micro-livraria .
          
          # Runs micro livraria in background
          docker run -d --rm -p 5000:5000 -p 3000:3000 micro-livraria
          
          # Runs guide automator
          docker run --rm -v $(pwd)/output:/usr/src/output -v $(pwd)/.guide-automator:/usr/src/guide-automator icaroerasmo/guide-automator-puppeteer -d -i /usr/src/guide-automator/livraria.md -cv /usr/src/guide-automator/cover.html -o /usr/src/output
      - name: Upload video
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: output/video.mp4
          asset_name: mything
          tag: ${{ github.ref }}
          overwrite: true
          body: "Micro livraria video"
